# Numpy

Una de las grandes carencias de Python es que no tiene arrays y las listas no son eficientes para trabajar con grandes cantidades de datos. Numpy es la biblioteca que permite la gestión eficiente de arrays multidimensionales. Además proporciona distintas utilidades relacionadas con el álgebra lineal, la generación de números aleatorios, la transformada de Fourier, etc.

http://www.numpy.org/

Los arrays tienen un tamaño fijo establecido cuando se crean y todos sus elementos son del mismo tipo. Proporcionan estrategias avanzadas de indexación que permiten acceder a partes del array sin duplicar los datos (vistas). También permiten vectorizar algunas operaciones para que se apliquen a varios elementos del array de forma eficiente.

## Creación de arrays y dimensiones

In [1]:
import numpy as np

# convertir una lista en un array
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(l)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# cambiar la forma de un array
a = a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# consultar las dimensiones
a.shape

(3, 3)

In [4]:
# creación de arrays a partir de sus dimensiones
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
# creación de un array a partir de un rango de valores [1..10)
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Acceso a elementos y vistas

In [8]:
# acceso a elementos individuales
print(a[0,0])
print(a[0,1])
print(a[2,2])

1
2
9


In [9]:
# asignación de valores
a[0,0] = 10
a

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [10]:
a[0,0] = 1
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# acceso a la fila 0 (vista)
a[0,:]

array([1, 2, 3])

In [12]:
# acceso a la columna 0 (vista)
a[:,0]

array([1, 4, 7])

In [13]:
# las vistas no modifican el array original
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# subarrays
a[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [15]:
# sólo filas pares
a[::2,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [16]:
# invertir el orden de las filas
a[::-1,:]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# cuidado, todas las vistas comparten el mismo array en memoria
b = a[:,0:2]
b

array([[1, 2],
       [4, 5],
       [7, 8]])

In [19]:
b[0,0] = 100
b

array([[100,   2],
       [  4,   5],
       [  7,   8]])

In [20]:
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

## Broadcasting

Podemos operar sobre elemento individuales de la forma habitual pero también podemos realizar operaciones sobre varios elementos del array de forma simultánea. Esto es mucho más eficiente que iterar sobre el array realizando las operaciones sobre los elementos individuales.

In [21]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# operar sobre un elemento individual
m[0,0] = 10
m

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
# operar sobre varios elementos simultáneamente
m = np.arange(1,10).reshape(3,3)
m[0:2,:] = 0
m

array([[0, 0, 0],
       [0, 0, 0],
       [7, 8, 9]])

In [24]:
# Operaciones con todos los elementos
m = np.arange(1,10).reshape(3,3)
m * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
2 ** m

array([[  2,   4,   8],
       [ 16,  32,  64],
       [128, 256, 512]])

In [26]:
# operaciones booleanas
m > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [27]:
# indexar mediante máscaras de booleanos (sigue siendo una vista)
m[m > 5]

array([6, 7, 8, 9])

In [28]:
# operaciones sobre una vista
m[m > 5] * 2

array([12, 14, 16, 18])

In [29]:
# modificar varios elementos del array
m[m>5] = m[m>5] * 2
m

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [14, 16, 18]])

## Otras operaciones sobre arrays

In [30]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# suma de todos los elementos
m.sum()

45

In [32]:
# suma por columnas
m.sum(axis=0)

array([12, 15, 18])

In [33]:
# suma por filas
m.sum(axis=1)

array([ 6, 15, 24])

In [34]:
# producto vectorial de dos matrices
np.dot(m, m)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])